In [1]:
# Import Dependencies
import pandas as pd
from pathlib import Path
import numpy as np

In [2]:
# Importing and reading csv files
ontario_csv= Path("Resources/ONTARIO.csv")
saskatoon_csv= Path("Resources/SASKATOON.csv")
aggregrate_csv = Path("Resources/AGGREGATE.csv")
bancroft_csv = Path("Resources/BANCROFT_AND_AREA.csv")
barrie_csv = Path("Resources/BARRIE_AND_DISTRICT.csv")
calgary_csv = Path("Resources/CALGARY.csv")
cambridge_csv = Path("Resources/CAMBRIDGE.csv")
chilliwack_csv = Path("Resources/CHILLIWACK_AND_DISTRICT.csv")
edmonton_csv = Path("Resources/EDMONTON.csv")
greater_vancouver_csv = Path("Resources/GREATER_VANCOUVER.csv")
grey_bruce_owen_sound_csv = Path("Resources/GREY_BRUCE_OWEN_SOUND.csv")
guelph_csv = Path("Resources/GUELPH_AND_DISTRICT.csv")
hamilton_csv = Path("Resources/HAMILTON_BURLINGTON.csv")
interior_bc_csv = Path("Resources/INTERIOR_BC.csv")
lower_mainland_csv = Path("Resources/LOWER_MAINLAND.csv")
newfoundland_csv = Path("Resources/NEWFOUNDLAND_AND_LABRADOR.csv")
ontario_csv = Path("Resources/ONTARIO.csv")
saskatchewan_csv = Path("Resources/SASKATCHEWAN.csv")
saskatoon_csv = Path("Resources/SASKATOON.csv")
vancouver_island_csv = Path("Resources/VANCOUVER_ISLAND.csv")
victoria_csv = Path("Resources/VICTORIA.csv")
winnipeg_csv = Path("Resources/WINNIPEG.csv")


# reading csv files
aggregrate_df = pd.read_csv(aggregrate_csv)
bancroft_df = pd.read_csv(bancroft_csv)
barrie_df = pd.read_csv(barrie_csv)
calgary_df = pd.read_csv(calgary_csv)
cambridge_df = pd.read_csv(cambridge_csv)
chilliwack_df = pd.read_csv(chilliwack_csv)
edmonton_df = pd.read_csv(edmonton_csv)
greater_vancouver_df = pd.read_csv(greater_vancouver_csv)
grey_bruce_owen_sound_df = pd.read_csv(grey_bruce_owen_sound_csv)
guelph_df = pd.read_csv(guelph_csv)
hamilton_df = pd.read_csv(hamilton_csv)
interior_bc_df = pd.read_csv(interior_bc_csv)
lower_mainland_df = pd.read_csv(lower_mainland_csv)
newfoundland_df = pd.read_csv(newfoundland_csv)
ontario_df = pd.read_csv(ontario_csv)
saskatchewan_df = pd.read_csv(saskatchewan_csv)
saskatoon_df = pd.read_csv(saskatoon_csv)
vancouver_island_df = pd.read_csv(vancouver_island_csv)
victoria_df = pd.read_csv(victoria_csv)
winnipeg_df = pd.read_csv(winnipeg_csv)

In [3]:
# removing NA values from the dataset
ontario_df= ontario_df.dropna()
saskatoon_df=saskatoon_df.dropna()
aggregrate_df = aggregrate_df.dropna()
bancroft_df = bancroft_df.dropna()
barrie_df = barrie_df.dropna()
calgary_df = calgary_df.dropna()
cambridge_df = cambridge_df.dropna()
chilliwack_df = chilliwack_df.dropna()
edmonton_df = edmonton_df.dropna()
greater_vancouver_df = greater_vancouver_df.dropna()
grey_bruce_owen_sound_df = grey_bruce_owen_sound_df.dropna()
guelph_df = guelph_df.dropna()
hamilton_df = hamilton_df.dropna()
interior_bc_df = interior_bc_df.dropna()
lower_mainland_df = lower_mainland_df.dropna()
newfoundland_df = newfoundland_df.dropna()
saskatchewan_df = saskatchewan_df.dropna()
vancouver_island_df = vancouver_island_df.dropna()
victoria_df = victoria_df.dropna()
winnipeg_df = winnipeg_df.dropna()

In [4]:
chilliwack_df

,Date,Composite_HPI_SA,Single_Family_HPI_SA,One_Storey_HPI_SA,Two_Storey_HPI_SA,Townhouse_HPI_SA,Apartment_HPI_SA,Composite_Benchmark_SA,Single_Family_Benchmark_SA,One_Storey_Benchmark_SA,Two_Storey_Benchmark_SA,Townhouse_Benchmark_SA,Apartment_Benchmark_SA
0,Jan 2005,100.0,100.0,100.0,100.0,100.0,100.0,206900.0,245300.0,218800.0,293100.0,158100.0,97700.0
1,Feb 2005,101.3,101.4,102.0,100.5,101.2,99.7,209500.0,248800.0,223100.0,294600.0,160000.0,97400.0
2,Mar 2005,103.0,103.5,105.2,101.0,101.9,99.4,213200.0,253900.0,230100.0,296100.0,161100.0,97100.0
3,Apr 2005,104.1,104.6,106.7,101.6,103.2,99.5,215400.0,256700.0,233500.0,297700.0,163200.0,97200.0
4,May 2005,104.4,104.9,106.7,102.1,104.1,99.6,216100.0,257200.0,233500.0,299400.0,164600.0,97300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,Aug 2023,360.0,368.6,375.0,351.6,385.5,423.7,744900.0,904200.0,820600.0,1030600.0,609500.0,414000.0
224,Sep 2023,365.0,375.3,400.5,336.9,390.1,422.2,755100.0,920600.0,876400.0,987500.0,616700.0,412500.0
225,Oct 2023,360.1,367.7,377.7,344.1,392.9,430.8,745000.0,901900.0,826400.0,1008700.0,621200.0,420900.0
226,Nov 2023,349.1,354.7,355.4,344.1,391.6,417.3,722300.0,870200.0,777600.0,1008600.0,619100.0,407700.0
227,Dec 2023,359.6,367.7,384.1,335.3,390.0,433.7,744000.0,902000.0,840400.0,982700.0,616600.0,423700.0

In [5]:
# ------------------------------------------
value = "Saskatchewan"
saskatoon_df["Geographical Location"] = value
# --------------------------------------------
# ------------------------------------------
val_ont = "Ontario"
ontario_df["Geographical Location"] = val_ont
# --------------------------------------------
# ------------------------------------------
val_aggr = "Aggregrate"
aggregrate_df["Geographical Location"] = val_aggr
# --------------------------------------------
# ------------------------------------------
val_bancroft = "Ontario"
bancroft_df["Geographical Location"] = val_bancroft
# --------------------------------------------
# ------------------------------------------
val_b = "Ontario"
barrie_df["Geographical Location"] = val_b
# --------------------------------------------
# ------------------------------------------
val_cal = "Alberta"
calgary_df["Geographical Location"] = val_cal
# --------------------------------------------
# ------------------------------------------
val_cam = "Ontario"
cambridge_df["Geographical Location"] = val_cam
# --------------------------------------------
# ------------------------------------------
val_c = "Vancouver"
chilliwack_df["Geographical Location"] = val_c
# --------------------------------------------
# ------------------------------------------
val_edm = "Alberta"
edmonton_df["Geographical Location"] = val_edm
# --------------------------------------------
# ------------------------------------------
val_van= "Vancouver"
greater_vancouver_df["Geographical Location"] = val_van
# --------------------------------------------
# ------------------------------------------
val_grey = "Ontario"
grey_bruce_owen_sound_df["Geographical Location"] = val_grey
# --------------------------------------------
# ------------------------------------------
val_guelph = "Ontario"
guelph_df["Geographical Location"] = val_guelph
# --------------------------------------------
# ------------------------------------------
val_hamil = "Ontario"
hamilton_df["Geographical Location"] = val_hamil
# --------------------------------------------
# ------------------------------------------
val_bc = "Vancouver"
interior_bc_df["Geographical Location"] = val_bc
# --------------------------------------------
# ------------------------------------------
val_lower = "Vancouver"
lower_mainland_df["Geographical Location"] = val_lower
# --------------------------------------------
# ------------------------------------------
val_new = "Newfoundland and Labrador"
newfoundland_df["Geographical Location"] = val_new
# --------------------------------------------
# ------------------------------------------
val_sask = "Saskatchewan"
saskatchewan_df["Geographical Location"] = val_sask
# --------------------------------------------
# ------------------------------------------
val_van = "Vancouver"
vancouver_island_df["Geographical Location"] = val_van
# --------------------------------------------
# ------------------------------------------
val_vic = "Vancouver"
victoria_df["Geographical Location"] = val_vic
# --------------------------------------------
# ------------------------------------------
val_winni = "Manitoba"
winnipeg_df["Geographical Location"] = val_winni
# --------------------------------------------

In [6]:
# Setting Geographical Loacation as index for all df

ontario_df.set_index("Geographical Location", inplace=True)
saskatoon_df.set_index("Geographical Location", inplace=True)
aggregrate_df.set_index("Geographical Location", inplace=True)
bancroft_df.set_index("Geographical Location", inplace=True)
barrie_df.set_index("Geographical Location", inplace=True)
calgary_df.set_index("Geographical Location", inplace=True)
cambridge_df.set_index("Geographical Location", inplace=True)
chilliwack_df.set_index("Geographical Location", inplace=True)
edmonton_df.set_index("Geographical Location", inplace=True)
greater_vancouver_df.set_index("Geographical Location", inplace=True)
grey_bruce_owen_sound_df.set_index("Geographical Location", inplace=True)
guelph_df.set_index("Geographical Location", inplace=True)
hamilton_df.set_index("Geographical Location", inplace=True)
interior_bc_df.set_index("Geographical Location", inplace=True)
lower_mainland_df.set_index("Geographical Location", inplace=True)
newfoundland_df.set_index("Geographical Location", inplace=True)
saskatchewan_df.set_index("Geographical Location", inplace=True)
vancouver_island_df.set_index("Geographical Location", inplace=True)
victoria_df.set_index("Geographical Location", inplace=True)
winnipeg_df.set_index("Geographical Location", inplace=True)

In [7]:
concat_df= pd.concat([ontario_df,saskatoon_df,aggregrate_df,
                      bancroft_df,barrie_df,calgary_df,cambridge_df,
                      chilliwack_df,edmonton_df,greater_vancouver_df,
                      grey_bruce_owen_sound_df, guelph_df,hamilton_df,
                      interior_bc_df,lower_mainland_df,newfoundland_df,
                      saskatchewan_df,vancouver_island_df,victoria_df,
                      winnipeg_df],axis=0)
concat_df

,Date,Composite_HPI_SA,Single_Family_HPI_SA,One_Storey_HPI_SA,Two_Storey_HPI_SA,Townhouse_HPI_SA,Apartment_HPI_SA,Composite_Benchmark_SA,Single_Family_Benchmark_SA,One_Storey_Benchmark_SA,Two_Storey_Benchmark_SA,Townhouse_Benchmark_SA,Apartment_Benchmark_SA
Geographical Location,,,,,,,,,,,,,
Ontario,Jan 2005,100.0,100.0,100.0,100.0,100.0,100.0,265700.0,287300.0,236200.0,312700.0,190400.0,184000.0
Ontario,Feb 2005,100.2,100.2,100.2,100.2,100.0,100.3,266300.0,287900.0,236600.0,313300.0,190400.0,184600.0
Ontario,Mar 2005,100.6,100.6,100.3,100.6,100.3,101.0,267300.0,289100.0,236800.0,314700.0,190900.0,185900.0
Ontario,Apr 2005,100.9,100.9,100.7,100.9,100.4,101.2,268000.0,290000.0,237900.0,315500.0,191200.0,186200.0
Ontario,May 2005,101.3,101.3,100.9,101.3,100.7,102.1,269100.0,291000.0,238300.0,316800.0,191700.0,187800.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Manitoba,Aug 2023,285.3,296.3,286.1,313.9,259.2,211.0,345200.0,363000.0,335600.0,405500.0,296800.0,223500.0
Manitoba,Sep 2023,285.7,296.4,285.3,315.2,261.3,214.4,345700.0,363100.0,334600.0,407300.0,299200.0,227000.0
Manitoba,Oct 2023,285.1,295.0,285.1,313.5,267.7,216.6,345000.0,361400.0,334400.0,405100.0,306500.0,229400.0
Manitoba,Nov 2023,282.4,292.5,283.1,308.4,266.0,214.1,341700.0,358300.0,332100.0,398400.0,304600.0,226700.0
Manitoba,Dec 2023,283.4,292.8,281.6,312.0,273.2,217.5,342900.0,358700.0,330300.0,403100.0,312800.0,230300.0

In [8]:
concat_df= concat_df.rename(columns={"Geographical Location": "Provience"})
concat_df

,Date,Composite_HPI_SA,Single_Family_HPI_SA,One_Storey_HPI_SA,Two_Storey_HPI_SA,Townhouse_HPI_SA,Apartment_HPI_SA,Composite_Benchmark_SA,Single_Family_Benchmark_SA,One_Storey_Benchmark_SA,Two_Storey_Benchmark_SA,Townhouse_Benchmark_SA,Apartment_Benchmark_SA
Geographical Location,,,,,,,,,,,,,
Ontario,Jan 2005,100.0,100.0,100.0,100.0,100.0,100.0,265700.0,287300.0,236200.0,312700.0,190400.0,184000.0
Ontario,Feb 2005,100.2,100.2,100.2,100.2,100.0,100.3,266300.0,287900.0,236600.0,313300.0,190400.0,184600.0
Ontario,Mar 2005,100.6,100.6,100.3,100.6,100.3,101.0,267300.0,289100.0,236800.0,314700.0,190900.0,185900.0
Ontario,Apr 2005,100.9,100.9,100.7,100.9,100.4,101.2,268000.0,290000.0,237900.0,315500.0,191200.0,186200.0
Ontario,May 2005,101.3,101.3,100.9,101.3,100.7,102.1,269100.0,291000.0,238300.0,316800.0,191700.0,187800.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Manitoba,Aug 2023,285.3,296.3,286.1,313.9,259.2,211.0,345200.0,363000.0,335600.0,405500.0,296800.0,223500.0
Manitoba,Sep 2023,285.7,296.4,285.3,315.2,261.3,214.4,345700.0,363100.0,334600.0,407300.0,299200.0,227000.0
Manitoba,Oct 2023,285.1,295.0,285.1,313.5,267.7,216.6,345000.0,361400.0,334400.0,405100.0,306500.0,229400.0
Manitoba,Nov 2023,282.4,292.5,283.1,308.4,266.0,214.1,341700.0,358300.0,332100.0,398400.0,304600.0,226700.0
Manitoba,Dec 2023,283.4,292.8,281.6,312.0,273.2,217.5,342900.0,358700.0,330300.0,403100.0,312800.0,230300.0

In [9]:
concat_df.columns
concat_df.dtypes

Date                           object
Composite_HPI_SA              float64
Single_Family_HPI_SA          float64
One_Storey_HPI_SA             float64
Two_Storey_HPI_SA             float64
Townhouse_HPI_SA              float64
Apartment_HPI_SA              float64
Composite_Benchmark_SA        float64
Single_Family_Benchmark_SA    float64
One_Storey_Benchmark_SA       float64
Two_Storey_Benchmark_SA       float64
Townhouse_Benchmark_SA        float64
Apartment_Benchmark_SA        float64
dtype: object

In [10]:
# # data formatting
# Index(['Date', 'Composite_HPI_SA', 'Single_Family_HPI_SA', 'One_Storey_HPI_SA','Two_Storey_HPI_SA', 'Townhouse_HPI_SA', 'Apartment_HPI_SA','Composite_Benchmark_SA', 'Single_Family_Benchmark_SA','One_Storey_Benchmark_SA', 'Two_Storey_Benchmark_SA', 'Townhouse_Benchmark_SA', 'Apartment_Benchmark_SA'],
#       dtype='object')

concat_df[['Composite_HPI_SA', 'Single_Family_HPI_SA',
            'One_Storey_HPI_SA','Two_Storey_HPI_SA', 
            'Townhouse_HPI_SA', 'Apartment_HPI_SA','Composite_Benchmark_SA', 
            'Single_Family_Benchmark_SA','One_Storey_Benchmark_SA', 
            'Two_Storey_Benchmark_SA', 'Townhouse_Benchmark_SA', 
            'Apartment_Benchmark_SA']] = concat_df[['Composite_HPI_SA', 'Single_Family_HPI_SA', 
                                                    'One_Storey_HPI_SA','Two_Storey_HPI_SA',
                                                      'Townhouse_HPI_SA', 'Apartment_HPI_SA','Composite_Benchmark_SA', 
                                                      'Single_Family_Benchmark_SA','One_Storey_Benchmark_SA',
                                                        'Two_Storey_Benchmark_SA', 'Townhouse_Benchmark_SA', 
                                                        'Apartment_Benchmark_SA']].astype(float)

concat_df

,Date,Composite_HPI_SA,Single_Family_HPI_SA,One_Storey_HPI_SA,Two_Storey_HPI_SA,Townhouse_HPI_SA,Apartment_HPI_SA,Composite_Benchmark_SA,Single_Family_Benchmark_SA,One_Storey_Benchmark_SA,Two_Storey_Benchmark_SA,Townhouse_Benchmark_SA,Apartment_Benchmark_SA
Geographical Location,,,,,,,,,,,,,
Ontario,Jan 2005,100.0,100.0,100.0,100.0,100.0,100.0,265700.0,287300.0,236200.0,312700.0,190400.0,184000.0
Ontario,Feb 2005,100.2,100.2,100.2,100.2,100.0,100.3,266300.0,287900.0,236600.0,313300.0,190400.0,184600.0
Ontario,Mar 2005,100.6,100.6,100.3,100.6,100.3,101.0,267300.0,289100.0,236800.0,314700.0,190900.0,185900.0
Ontario,Apr 2005,100.9,100.9,100.7,100.9,100.4,101.2,268000.0,290000.0,237900.0,315500.0,191200.0,186200.0
Ontario,May 2005,101.3,101.3,100.9,101.3,100.7,102.1,269100.0,291000.0,238300.0,316800.0,191700.0,187800.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Manitoba,Aug 2023,285.3,296.3,286.1,313.9,259.2,211.0,345200.0,363000.0,335600.0,405500.0,296800.0,223500.0
Manitoba,Sep 2023,285.7,296.4,285.3,315.2,261.3,214.4,345700.0,363100.0,334600.0,407300.0,299200.0,227000.0
Manitoba,Oct 2023,285.1,295.0,285.1,313.5,267.7,216.6,345000.0,361400.0,334400.0,405100.0,306500.0,229400.0
Manitoba,Nov 2023,282.4,292.5,283.1,308.4,266.0,214.1,341700.0,358300.0,332100.0,398400.0,304600.0,226700.0
Manitoba,Dec 2023,283.4,292.8,281.6,312.0,273.2,217.5,342900.0,358700.0,330300.0,403100.0,312800.0,230300.0

In [11]:
# renaming columns 

concat_df= concat_df.rename(columns={"Composite_HPI_SA" : "Composite HPI",
                                      "Single_Family_HPI_SA" : "Single Family HPI",
                                      "One_Storey_HPI_SA" : "One Storey HPI",
                                      "Two_Storey_HPI_SA" : "Two Storey HPI",
                                      "Townhouse_HPI_SA" : "Townhouse HPI",
                                      "Apartment_HPI_SA": "Apartment HPI",
                                      "Composite_Benchmark_SA" : "Composite House",
                                      "Single_Family_Benchmark_SA" : "Single Family House",
                                      "One_Storey_Benchmark_SA" : "One Storey House",
                                      "Two_Storey_Benchmark_SA" : "Two Storey House",
                                      "Townhouse_Benchmark_SA" : "Townhouse House",
                                      "Apartment_Benchmark_SA": "Apartment House",})

In [12]:
concat_df.dtypes

Date                    object
Composite HPI          float64
Single Family HPI      float64
One Storey HPI         float64
Two Storey HPI         float64
Townhouse HPI          float64
Apartment HPI          float64
Composite House        float64
Single Family House    float64
One Storey House       float64
Two Storey House       float64
Townhouse House        float64
Apartment House        float64
dtype: object

In [13]:
concat_df=concat_df.reset_index()

In [20]:
concat_df= concat_df.rename(columns={"Geographical Location": "Provience"})
concat_df

,Provience,Date,Composite HPI,Single Family HPI,One Storey HPI,Two Storey HPI,Townhouse HPI,Apartment HPI,Composite House,Single Family House,One Storey House,Two Storey House,Townhouse House,Apartment House,Month,Year
0,Ontario,Jan 2005,100.0,100.0,100.0,100.0,100.0,100.0,265700.0,287300.0,236200.0,312700.0,190400.0,184000.0,Jan,2005
1,Ontario,Feb 2005,100.2,100.2,100.2,100.2,100.0,100.3,266300.0,287900.0,236600.0,313300.0,190400.0,184600.0,Feb,2005
2,Ontario,Mar 2005,100.6,100.6,100.3,100.6,100.3,101.0,267300.0,289100.0,236800.0,314700.0,190900.0,185900.0,Mar,2005
3,Ontario,Apr 2005,100.9,100.9,100.7,100.9,100.4,101.2,268000.0,290000.0,237900.0,315500.0,191200.0,186200.0,Apr,2005
4,Ontario,May 2005,101.3,101.3,100.9,101.3,100.7,102.1,269100.0,291000.0,238300.0,316800.0,191700.0,187800.0,May,2005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4555,Manitoba,Aug 2023,285.3,296.3,286.1,313.9,259.2,211.0,345200.0,363000.0,335600.0,405500.0,296800.0,223500.0,Aug,2023
4556,Manitoba,Sep 2023,285.7,296.4,285.3,315.2,261.3,214.4,345700.0,363100.0,334600.0,407300.0,299200.0,227000.0,Sep,2023
4557,Manitoba,Oct 2023,285.1,295.0,285.1,313.5,267.7,216.6,345000.0,361400.0,334400.0,405100.0,306500.0,229400.0,Oct,2023
4558,Manitoba,Nov 2023,282.4,292.5,283.1,308.4,266.0,214.1,341700.0,358300.0,332100.0,398400.0,304600.0,226700.0,Nov,2023
4559,Manitoba,Dec 2023,283.4,292.8,281.6,312.0,273.2,217.5,342900.0,358700.0,330300.0,403100.0,312800.0,230300.0,Dec,2023

In [15]:
concat_df.to_csv("Output/real_estate_clean.csv",
                  encoding="utf-8", index=False, header=True)

In [16]:
concat_df["Date"]

0       Jan 2005
1       Feb 2005
2       Mar 2005
3       Apr 2005
4       May 2005
          ...
4555    Aug 2023
4556    Sep 2023
4557    Oct 2023
4558    Nov 2023
4559    Dec 2023
Name: Date, Length: 4560, dtype: object

In [17]:
# Extracting year from Date
concat_df[["Month","Year"]]= concat_df["Date"].str.split(" ",expand=True)
concat_df.head()

,Geographical Location,Date,Composite HPI,Single Family HPI,One Storey HPI,Two Storey HPI,Townhouse HPI,Apartment HPI,Composite House,Single Family House,One Storey House,Two Storey House,Townhouse House,Apartment House,Month,Year
0,Ontario,Jan 2005,100.0,100.0,100.0,100.0,100.0,100.0,265700.0,287300.0,236200.0,312700.0,190400.0,184000.0,Jan,2005
1,Ontario,Feb 2005,100.2,100.2,100.2,100.2,100.0,100.3,266300.0,287900.0,236600.0,313300.0,190400.0,184600.0,Feb,2005
2,Ontario,Mar 2005,100.6,100.6,100.3,100.6,100.3,101.0,267300.0,289100.0,236800.0,314700.0,190900.0,185900.0,Mar,2005
3,Ontario,Apr 2005,100.9,100.9,100.7,100.9,100.4,101.2,268000.0,290000.0,237900.0,315500.0,191200.0,186200.0,Apr,2005
4,Ontario,May 2005,101.3,101.3,100.9,101.3,100.7,102.1,269100.0,291000.0,238300.0,316800.0,191700.0,187800.0,May,2005

In [18]:
concat_df[['Composite HPI', 'Single Family HPI',
            'One Storey HPI','Two Storey HPI', 
            'Townhouse HPI', 'Apartment HPI','Composite House', 
            'Single Family House','One Storey House', 
            'Two Storey House', 'Townhouse House', 
            'Apartment House']] = concat_df[['Composite HPI', 'Single Family HPI', 
                                                    'One Storey HPI','Two Storey HPI',
                                                      'Townhouse HPI', 'Apartment HPI','Composite House', 
                                                      'Single Family House','One Storey House',
                                                        'Two Storey House', 'Townhouse House', 
                                                        'Apartment House']].astype(float)

concat_df

,Geographical Location,Date,Composite HPI,Single Family HPI,One Storey HPI,Two Storey HPI,Townhouse HPI,Apartment HPI,Composite House,Single Family House,One Storey House,Two Storey House,Townhouse House,Apartment House,Month,Year
0,Ontario,Jan 2005,100.0,100.0,100.0,100.0,100.0,100.0,265700.0,287300.0,236200.0,312700.0,190400.0,184000.0,Jan,2005
1,Ontario,Feb 2005,100.2,100.2,100.2,100.2,100.0,100.3,266300.0,287900.0,236600.0,313300.0,190400.0,184600.0,Feb,2005
2,Ontario,Mar 2005,100.6,100.6,100.3,100.6,100.3,101.0,267300.0,289100.0,236800.0,314700.0,190900.0,185900.0,Mar,2005
3,Ontario,Apr 2005,100.9,100.9,100.7,100.9,100.4,101.2,268000.0,290000.0,237900.0,315500.0,191200.0,186200.0,Apr,2005
4,Ontario,May 2005,101.3,101.3,100.9,101.3,100.7,102.1,269100.0,291000.0,238300.0,316800.0,191700.0,187800.0,May,2005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4555,Manitoba,Aug 2023,285.3,296.3,286.1,313.9,259.2,211.0,345200.0,363000.0,335600.0,405500.0,296800.0,223500.0,Aug,2023
4556,Manitoba,Sep 2023,285.7,296.4,285.3,315.2,261.3,214.4,345700.0,363100.0,334600.0,407300.0,299200.0,227000.0,Sep,2023
4557,Manitoba,Oct 2023,285.1,295.0,285.1,313.5,267.7,216.6,345000.0,361400.0,334400.0,405100.0,306500.0,229400.0,Oct,2023
4558,Manitoba,Nov 2023,282.4,292.5,283.1,308.4,266.0,214.1,341700.0,358300.0,332100.0,398400.0,304600.0,226700.0,Nov,2023
4559,Manitoba,Dec 2023,283.4,292.8,281.6,312.0,273.2,217.5,342900.0,358700.0,330300.0,403100.0,312800.0,230300.0,Dec,2023

In [21]:
real_estate_final_df= concat_df.groupby(["Year","Provience"])
real_estate_by_year_df= pd.DataFrame(real_estate_final_df[['Composite HPI', 'Single Family HPI',
                                                        'One Storey HPI','Two Storey HPI', 
                                                        'Townhouse HPI', 'Apartment HPI','Composite House', 
                                                        'Single Family House','One Storey House', 
                                                        'Two Storey House', 'Townhouse House', 
                                                        'Apartment House']].median())

real_estate_by_year_df

                                Composite HPI  Single Family HPI  \
Year Provience
2005 Aggregrate                        102.25             102.05
     Alberta                           100.45             100.30
     Manitoba                          104.30             104.35
     Newfoundland and Labrador         103.00             103.00
     Ontario                           101.30             101.40
...                                       ...                ...
2023 Manitoba                          281.95             292.40
     Newfoundland and Labrador         217.70             218.90
     Ontario                           355.05             364.15
     Saskatchewan                      289.00             305.05
     Vancouver                         331.70             346.45

                                One Storey HPI  Two Storey HPI  Townhouse HPI  \
Year Provience
2005 Aggregrate                         102.25          101.80         101.90
     Alberta                            100.35          100.20          99.60
     Manitoba                           104.70          104.15         102.30
     Newfoundland and Labrador          105.45          100.75         101.35
     Ontario                            101.05          101.80         101.75
...                                        ...             ...            ...
2023 Manitoba                           282.15          308.85         253.60
     Newfoundland and Labrador          231.85          212.55         211.65
     Ontario                            363.25          356.10         403.95
     Saskatchewan                       291.40          292.25         260.45
     Vancouver                          344.80          339.05         363.05

                                Apartment HPI  Composite House  \
Year Provience
2005 Aggregrate                        103.20         246350.0
     Alberta                           100.20         202800.0
     Manitoba                          102.80         126200.0
     Newfoundland and Labrador         100.00         134400.0
     Ontario                           101.45         216100.0
...                                       ...              ...
2023 Manitoba                          209.65         341150.0
     Newfoundland and Labrador         210.95         284150.0
     Ontario                           336.35         792200.0
     Saskatchewan                      246.60         348650.0
     Vancouver                         347.95         797450.0

                                Single Family House  One Storey House  \
Year Provience
2005 Aggregrate                            266700.0          213400.0
     Alberta                               227200.0          201400.0
     Manitoba                              127850.0          122800.0
     Newfoundland and Labrador             134600.0          119450.0
     Ontario                               223900.0          217200.0
...                                             ...               ...
2023 Manitoba                              358200.0          330950.0
     Newfoundland and Labrador             286050.0          262700.0
     Ontario                               849150.0          776150.0
     Saskatchewan                          381150.0          326900.0
     Vancouver                            1010050.0          935700.0

                                Two Storey House  Townhouse House  \
Year Provience
2005 Aggregrate                         309500.0         206400.0
     Alberta                            259800.0         145450.0
     Manitoba                           134550.0         117150.0
     Newfoundland and Labrador          156300.0         131300.0
     Ontario                            228150.0         167750.0
...                                          ...              ...
2023 Manitoba                           399050.0         290400.0
     Newfoundland and Labrador          329700.0         274050.0
     Ontario                            883250.0         661350.0
     Saskatchewan                       461000.0         289000.0
     Vancouver                         1129050.0         711650.0

                                Apartment House
Year Provience
2005 Aggregrate                        180050.0
     Alberta                           128550.0
     Manitoba                          108850.0
     Newfoundland and Labrador         107700.0
     Ontario                           163300.0
...                                         ...
2023 Manitoba                          222050.0
     Newfoundland and Labrador         227200.0
     Ontario                           530450.0
     Saskatchewan                      217150.0
     Vancouver                         502050.0

[133 rows x 12 columns]