In [1]:
# Import Dependencies
import pandas as pd
from pathlib import Path

In [2]:
# Importing and reading csv files
ontario_csv= Path("Resources/ONTARIO.csv")
saskatoon_csv= Path("Resources/SASKATOON.csv")
aggregrate_csv = Path("Resources/AGGREGATE.csv")
bancroft_csv = Path("Resources/BANCROFT_AND_AREA.csv")
barrie_csv = Path("Resources/BARRIE_AND_DISTRICT.csv")
calgary_csv = Path("Resources/CALGARY.csv")
cambridge_csv = Path("Resources/CAMBRIDGE.csv")
chilliwack_csv = Path("Resources/CHILLIWACK_AND_DISTRICT.csv")
edmonton_csv = Path("Resources/EDMONTON.csv")
greater_vancouver_csv = Path("Resources/GREATER_VANCOUVER.csv")
grey_bruce_owen_sound_csv = Path("Resources/GREY_BRUCE_OWEN_SOUND.csv")
guelph_csv = Path("Resources/GUELPH_AND_DISTRICT.csv")
hamilton_csv = Path("Resources/HAMILTON_BURLINGTON.csv")
interior_bc_csv = Path("Resources/INTERIOR_BC.csv")
lower_mainland_csv = Path("Resources/LOWER_MAINLAND.csv")
newfoundland_csv = Path("Resources/NEWFOUNDLAND_AND_LABRADOR.csv")
ontario_csv = Path("Resources/ONTARIO.csv")
saskatchewan_csv = Path("Resources/SASKATCHEWAN.csv")
saskatoon_csv = Path("Resources/SASKATOON.csv")
vancouver_island_csv = Path("Resources/VANCOUVER_ISLAND.csv")
victoria_csv = Path("Resources/VICTORIA.csv")
winnipeg_csv = Path("Resources/WINNIPEG.csv")


# reading csv files
aggregrate_df = pd.read_csv(aggregrate_csv)
bancroft_df = pd.read_csv(bancroft_csv)
barrie_df = pd.read_csv(barrie_csv)
calgary_df = pd.read_csv(calgary_csv)
cambridge_df = pd.read_csv(cambridge_csv)
chilliwack_df = pd.read_csv(chilliwack_csv)
edmonton_df = pd.read_csv(edmonton_csv)
greater_vancouver_df = pd.read_csv(greater_vancouver_csv)
grey_bruce_owen_sound_df = pd.read_csv(grey_bruce_owen_sound_csv)
guelph_df = pd.read_csv(guelph_csv)
hamilton_df = pd.read_csv(hamilton_csv)
interior_bc_df = pd.read_csv(interior_bc_csv)
lower_mainland_df = pd.read_csv(lower_mainland_csv)
newfoundland_df = pd.read_csv(newfoundland_csv)
ontario_df = pd.read_csv(ontario_csv)
saskatchewan_df = pd.read_csv(saskatchewan_csv)
saskatoon_df = pd.read_csv(saskatoon_csv)
vancouver_island_df = pd.read_csv(vancouver_island_csv)
victoria_df = pd.read_csv(victoria_csv)
winnipeg_df = pd.read_csv(winnipeg_csv)

In [3]:
# removing NA values from the dataset
ontario_df.dropna()
saskatoon_df.dropna()
aggregrate_df = aggregrate_df.dropna()
bancroft_df = bancroft_df.dropna()
barrie_df = barrie_df.dropna()
calgary_df = calgary_df.dropna()
cambridge_df = cambridge_df.dropna()
chiiliwach_df = chilliwack_df.dropna()
edmonton_df = edmonton_df.dropna()
chilliwack_df=chilliwack_df.dropna()
greater_vancouver_df = greater_vancouver_df.dropna()
grey_bruce_owen_sound_df = grey_bruce_owen_sound_df.dropna()
guelph_df = guelph_df.dropna()
hamilton_df = hamilton_df.dropna()
interior_bc_df = interior_bc_df.dropna()
lower_mainland_df = lower_mainland_df.dropna()
newfoundland_df = newfoundland_df.dropna()
saskatchewan_df = saskatchewan_df.dropna()
vancouver_island_df = vancouver_island_df.dropna()
victoria_df = victoria_df.dropna()
winnipeg_df = winnipeg_df.dropna()

In [12]:
# ------------------------------------------
value = "Saskatchewan"
saskatoon_df["Geographical Location"] = value
# --------------------------------------------
# ------------------------------------------
val_ont = "Ontario"
ontario_df["Geographical Location"] = val_ont
# --------------------------------------------
# ------------------------------------------
val_aggr = "Aggregrate"
aggregrate_df["Geographical Location"] = val_aggr
# --------------------------------------------
# ------------------------------------------
val_bancroft = "Ontario"
bancroft_df["Geographical Location"] = val_bancroft
# --------------------------------------------
# ------------------------------------------
val_b = "Ontario"
barrie_df["Geographical Location"] = val_b
# --------------------------------------------
# ------------------------------------------
val_cal = "Alberta"
calgary_df["Geographical Location"] = val_cal
# --------------------------------------------
# ------------------------------------------
val_cam = "Ontario"
cambridge_df["Geographical Location"] = val_cam
# --------------------------------------------
# ------------------------------------------
val_chilliwack = "Vancouver"
chiiliwach_df["Geographical Location"] = val_chilliwack
# --------------------------------------------
# ------------------------------------------
val_edm = "Alberta"
edmonton_df["Geographical Location"] = val_edm
# --------------------------------------------
# ------------------------------------------
val_van= "Vancouver"
greater_vancouver_df["Geographical Location"] = val_van
# --------------------------------------------
# ------------------------------------------
val_grey = "Ontario"
grey_bruce_owen_sound_df["Geographical Location"] = val_grey
# --------------------------------------------
# ------------------------------------------
val_guelph = "Ontario"
guelph_df["Geographical Location"] = val_guelph
# --------------------------------------------
# ------------------------------------------
val_hamil = "Ontario"
hamilton_df["Geographical Location"] = val_hamil
# --------------------------------------------
# ------------------------------------------
val_bc = "Vancouver"
interior_bc_df["Geographical Location"] = val_bc
# --------------------------------------------
# ------------------------------------------
val_lower = "Vancouver"
lower_mainland_df["Geographical Location"] = val_lower
# --------------------------------------------
# ------------------------------------------
val_new = "Newfoundland and Labrador"
newfoundland_df["Geographical Location"] = val_new
# --------------------------------------------
# ------------------------------------------
val_sask = "Saskatchewan"
saskatchewan_df["Geographical Location"] = val_sask
# --------------------------------------------
# ------------------------------------------
val_van = "Vancouver"
vancouver_island_df["Geographical Location"] = val_van
# --------------------------------------------
# ------------------------------------------
val_vic = "Vancouver"
victoria_df["Geographical Location"] = val_vic
# --------------------------------------------
# ------------------------------------------
val_winni = "Manitoba"
winnipeg_df["Geographical Location"] = val_winni
# --------------------------------------------

In [13]:
chiiliwach_df

,Date,Composite_HPI_SA,Single_Family_HPI_SA,One_Storey_HPI_SA,Two_Storey_HPI_SA,Townhouse_HPI_SA,Apartment_HPI_SA,Composite_Benchmark_SA,Single_Family_Benchmark_SA,One_Storey_Benchmark_SA,Two_Storey_Benchmark_SA,Townhouse_Benchmark_SA,Apartment_Benchmark_SA,Geographical Location
Geographical Location,,,,,,,,,,,,,,
Chiiliwach,Jan 2005,100.0,100.0,100.0,100.0,100.0,100.0,206900.0,245300.0,218800.0,293100.0,158100.0,97700.0,Vancouver
Chiiliwach,Feb 2005,101.3,101.4,102.0,100.5,101.2,99.7,209500.0,248800.0,223100.0,294600.0,160000.0,97400.0,Vancouver
Chiiliwach,Mar 2005,103.0,103.5,105.2,101.0,101.9,99.4,213200.0,253900.0,230100.0,296100.0,161100.0,97100.0,Vancouver
Chiiliwach,Apr 2005,104.1,104.6,106.7,101.6,103.2,99.5,215400.0,256700.0,233500.0,297700.0,163200.0,97200.0,Vancouver
Chiiliwach,May 2005,104.4,104.9,106.7,102.1,104.1,99.6,216100.0,257200.0,233500.0,299400.0,164600.0,97300.0,Vancouver
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Chiiliwach,Aug 2023,360.0,368.6,375.0,351.6,385.5,423.7,744900.0,904200.0,820600.0,1030600.0,609500.0,414000.0,Vancouver
Chiiliwach,Sep 2023,365.0,375.3,400.5,336.9,390.1,422.2,755100.0,920600.0,876400.0,987500.0,616700.0,412500.0,Vancouver
Chiiliwach,Oct 2023,360.1,367.7,377.7,344.1,392.9,430.8,745000.0,901900.0,826400.0,1008700.0,621200.0,420900.0,Vancouver
Chiiliwach,Nov 2023,349.1,354.7,355.4,344.1,391.6,417.3,722300.0,870200.0,777600.0,1008600.0,619100.0,407700.0,Vancouver
Chiiliwach,Dec 2023,359.6,367.7,384.1,335.3,390.0,433.7,744000.0,902000.0,840400.0,982700.0,616600.0,423700.0,Vancouver

In [6]:
# Setting Geographical Loacation as index for all df

ontario_df.set_index("Geographical Location", inplace=True)
saskatoon_df.set_index("Geographical Location", inplace=True)
aggregrate_df.set_index("Geographical Location", inplace=True)
bancroft_df.set_index("Geographical Location", inplace=True)
barrie_df.set_index("Geographical Location", inplace=True)
calgary_df.set_index("Geographical Location", inplace=True)
cambridge_df.set_index("Geographical Location", inplace=True)
chiiliwach_df.set_index("Geographical Location", inplace=True)
edmonton_df.set_index("Geographical Location", inplace=True)
greater_vancouver_df.set_index("Geographical Location", inplace=True)
grey_bruce_owen_sound_df.set_index("Geographical Location", inplace=True)
guelph_df.set_index("Geographical Location", inplace=True)
hamilton_df.set_index("Geographical Location", inplace=True)
interior_bc_df.set_index("Geographical Location", inplace=True)
lower_mainland_df.set_index("Geographical Location", inplace=True)
newfoundland_df.set_index("Geographical Location", inplace=True)
saskatchewan_df.set_index("Geographical Location", inplace=True)
vancouver_island_df.set_index("Geographical Location", inplace=True)
victoria_df.set_index("Geographical Location", inplace=True)
winnipeg_df.set_index("Geographical Location", inplace=True)

In [8]:
concat_df= pd.concat([ontario_df,saskatoon_df,aggregrate_df,
                      bancroft_df,barrie_df,calgary_df,cambridge_df,
                      chilliwack_df,edmonton_df,greater_vancouver_df,
                      grey_bruce_owen_sound_df, guelph_df,hamilton_df,
                      interior_bc_df,lower_mainland_df,newfoundland_df,
                      saskatchewan_df,vancouver_island_df,victoria_df,
                      winnipeg_df],axis=0)
concat_df

,Date,Composite_HPI_SA,Single_Family_HPI_SA,One_Storey_HPI_SA,Two_Storey_HPI_SA,Townhouse_HPI_SA,Apartment_HPI_SA,Composite_Benchmark_SA,Single_Family_Benchmark_SA,One_Storey_Benchmark_SA,Two_Storey_Benchmark_SA,Townhouse_Benchmark_SA,Apartment_Benchmark_SA
Ontario,Jan 2005,100.0,100.0,100.0,100.0,100.0,100.0,265700.0,287300.0,236200.0,312700.0,190400.0,184000.0
Ontario,Feb 2005,100.2,100.2,100.2,100.2,100.0,100.3,266300.0,287900.0,236600.0,313300.0,190400.0,184600.0
Ontario,Mar 2005,100.6,100.6,100.3,100.6,100.3,101.0,267300.0,289100.0,236800.0,314700.0,190900.0,185900.0
Ontario,Apr 2005,100.9,100.9,100.7,100.9,100.4,101.2,268000.0,290000.0,237900.0,315500.0,191200.0,186200.0
Ontario,May 2005,101.3,101.3,100.9,101.3,100.7,102.1,269100.0,291000.0,238300.0,316800.0,191700.0,187800.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Winnipeg,Aug 2023,285.3,296.3,286.1,313.9,259.2,211.0,345200.0,363000.0,335600.0,405500.0,296800.0,223500.0
Winnipeg,Sep 2023,285.7,296.4,285.3,315.2,261.3,214.4,345700.0,363100.0,334600.0,407300.0,299200.0,227000.0
Winnipeg,Oct 2023,285.1,295.0,285.1,313.5,267.7,216.6,345000.0,361400.0,334400.0,405100.0,306500.0,229400.0
Winnipeg,Nov 2023,282.4,292.5,283.1,308.4,266.0,214.1,341700.0,358300.0,332100.0,398400.0,304600.0,226700.0
Winnipeg,Dec 2023,283.4,292.8,281.6,312.0,273.2,217.5,342900.0,358700.0,330300.0,403100.0,312800.0,230300.0

In [15]:
cleaning_df= concat_df.rename(columns={"Geographical Location": "Provience",})
cleaning_df

,Date,Composite_HPI_SA,Single_Family_HPI_SA,One_Storey_HPI_SA,Two_Storey_HPI_SA,Townhouse_HPI_SA,Apartment_HPI_SA,Composite_Benchmark_SA,Single_Family_Benchmark_SA,One_Storey_Benchmark_SA,Two_Storey_Benchmark_SA,Townhouse_Benchmark_SA,Apartment_Benchmark_SA
Ontario,Jan 2005,$100.00,$100.00,$100.00,$100.00,$100.00,$100.00,"$265,700.00","$287,300.00","$236,200.00","$312,700.00","$190,400.00","$184,000.00"
Ontario,Feb 2005,$100.20,$100.20,$100.20,$100.20,$100.00,$100.30,"$266,300.00","$287,900.00","$236,600.00","$313,300.00","$190,400.00","$184,600.00"
Ontario,Mar 2005,$100.60,$100.60,$100.30,$100.60,$100.30,$101.00,"$267,300.00","$289,100.00","$236,800.00","$314,700.00","$190,900.00","$185,900.00"
Ontario,Apr 2005,$100.90,$100.90,$100.70,$100.90,$100.40,$101.20,"$268,000.00","$290,000.00","$237,900.00","$315,500.00","$191,200.00","$186,200.00"
Ontario,May 2005,$101.30,$101.30,$100.90,$101.30,$100.70,$102.10,"$269,100.00","$291,000.00","$238,300.00","$316,800.00","$191,700.00","$187,800.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Winnipeg,Aug 2023,$285.30,$296.30,$286.10,$313.90,$259.20,$211.00,"$345,200.00","$363,000.00","$335,600.00","$405,500.00","$296,800.00","$223,500.00"
Winnipeg,Sep 2023,$285.70,$296.40,$285.30,$315.20,$261.30,$214.40,"$345,700.00","$363,100.00","$334,600.00","$407,300.00","$299,200.00","$227,000.00"
Winnipeg,Oct 2023,$285.10,$295.00,$285.10,$313.50,$267.70,$216.60,"$345,000.00","$361,400.00","$334,400.00","$405,100.00","$306,500.00","$229,400.00"
Winnipeg,Nov 2023,$282.40,$292.50,$283.10,$308.40,$266.00,$214.10,"$341,700.00","$358,300.00","$332,100.00","$398,400.00","$304,600.00","$226,700.00"
Winnipeg,Dec 2023,$283.40,$292.80,$281.60,$312.00,$273.20,$217.50,"$342,900.00","$358,700.00","$330,300.00","$403,100.00","$312,800.00","$230,300.00"

In [9]:
concat_df.columns
concat_df.dtypes

Date                           object
Composite_HPI_SA              float64
Single_Family_HPI_SA          float64
One_Storey_HPI_SA             float64
Two_Storey_HPI_SA             float64
Townhouse_HPI_SA              float64
Apartment_HPI_SA              float64
Composite_Benchmark_SA        float64
Single_Family_Benchmark_SA    float64
One_Storey_Benchmark_SA       float64
Two_Storey_Benchmark_SA       float64
Townhouse_Benchmark_SA        float64
Apartment_Benchmark_SA        float64
dtype: object

In [10]:
# # data formatting
# Index(['Date', 'Composite_HPI_SA', 'Single_Family_HPI_SA', 'One_Storey_HPI_SA','Two_Storey_HPI_SA', 'Townhouse_HPI_SA', 'Apartment_HPI_SA','Composite_Benchmark_SA', 'Single_Family_Benchmark_SA','One_Storey_Benchmark_SA', 'Two_Storey_Benchmark_SA', 'Townhouse_Benchmark_SA', 'Apartment_Benchmark_SA'],
#       dtype='object')

concat_df[['Composite_HPI_SA', 'Single_Family_HPI_SA',
            'One_Storey_HPI_SA','Two_Storey_HPI_SA', 
            'Townhouse_HPI_SA', 'Apartment_HPI_SA','Composite_Benchmark_SA', 
            'Single_Family_Benchmark_SA','One_Storey_Benchmark_SA', 
            'Two_Storey_Benchmark_SA', 'Townhouse_Benchmark_SA', 
            'Apartment_Benchmark_SA']] = concat_df[['Composite_HPI_SA', 'Single_Family_HPI_SA', 
                                                    'One_Storey_HPI_SA','Two_Storey_HPI_SA',
                                                      'Townhouse_HPI_SA', 'Apartment_HPI_SA','Composite_Benchmark_SA', 
                                                      'Single_Family_Benchmark_SA','One_Storey_Benchmark_SA',
                                                        'Two_Storey_Benchmark_SA', 'Townhouse_Benchmark_SA', 
                                                        'Apartment_Benchmark_SA']].astype(float).map("${:,.2f}".format)

concat_df

,Date,Composite_HPI_SA,Single_Family_HPI_SA,One_Storey_HPI_SA,Two_Storey_HPI_SA,Townhouse_HPI_SA,Apartment_HPI_SA,Composite_Benchmark_SA,Single_Family_Benchmark_SA,One_Storey_Benchmark_SA,Two_Storey_Benchmark_SA,Townhouse_Benchmark_SA,Apartment_Benchmark_SA
Ontario,Jan 2005,$100.00,$100.00,$100.00,$100.00,$100.00,$100.00,"$265,700.00","$287,300.00","$236,200.00","$312,700.00","$190,400.00","$184,000.00"
Ontario,Feb 2005,$100.20,$100.20,$100.20,$100.20,$100.00,$100.30,"$266,300.00","$287,900.00","$236,600.00","$313,300.00","$190,400.00","$184,600.00"
Ontario,Mar 2005,$100.60,$100.60,$100.30,$100.60,$100.30,$101.00,"$267,300.00","$289,100.00","$236,800.00","$314,700.00","$190,900.00","$185,900.00"
Ontario,Apr 2005,$100.90,$100.90,$100.70,$100.90,$100.40,$101.20,"$268,000.00","$290,000.00","$237,900.00","$315,500.00","$191,200.00","$186,200.00"
Ontario,May 2005,$101.30,$101.30,$100.90,$101.30,$100.70,$102.10,"$269,100.00","$291,000.00","$238,300.00","$316,800.00","$191,700.00","$187,800.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Winnipeg,Aug 2023,$285.30,$296.30,$286.10,$313.90,$259.20,$211.00,"$345,200.00","$363,000.00","$335,600.00","$405,500.00","$296,800.00","$223,500.00"
Winnipeg,Sep 2023,$285.70,$296.40,$285.30,$315.20,$261.30,$214.40,"$345,700.00","$363,100.00","$334,600.00","$407,300.00","$299,200.00","$227,000.00"
Winnipeg,Oct 2023,$285.10,$295.00,$285.10,$313.50,$267.70,$216.60,"$345,000.00","$361,400.00","$334,400.00","$405,100.00","$306,500.00","$229,400.00"
Winnipeg,Nov 2023,$282.40,$292.50,$283.10,$308.40,$266.00,$214.10,"$341,700.00","$358,300.00","$332,100.00","$398,400.00","$304,600.00","$226,700.00"
Winnipeg,Dec 2023,$283.40,$292.80,$281.60,$312.00,$273.20,$217.50,"$342,900.00","$358,700.00","$330,300.00","$403,100.00","$312,800.00","$230,300.00"

In [23]:
concat_df=concat_df.reset_index()

In [24]:
concat_df= concat_df.rename(columns={"index": "Provience",})
concat_df

,Provience,Date,Composite_HPI_SA,Single_Family_HPI_SA,One_Storey_HPI_SA,Two_Storey_HPI_SA,Townhouse_HPI_SA,Apartment_HPI_SA,Composite_Benchmark_SA,Single_Family_Benchmark_SA,One_Storey_Benchmark_SA,Two_Storey_Benchmark_SA,Townhouse_Benchmark_SA,Apartment_Benchmark_SA
0,Ontario,Jan 2005,$100.00,$100.00,$100.00,$100.00,$100.00,$100.00,"$265,700.00","$287,300.00","$236,200.00","$312,700.00","$190,400.00","$184,000.00"
1,Ontario,Feb 2005,$100.20,$100.20,$100.20,$100.20,$100.00,$100.30,"$266,300.00","$287,900.00","$236,600.00","$313,300.00","$190,400.00","$184,600.00"
2,Ontario,Mar 2005,$100.60,$100.60,$100.30,$100.60,$100.30,$101.00,"$267,300.00","$289,100.00","$236,800.00","$314,700.00","$190,900.00","$185,900.00"
3,Ontario,Apr 2005,$100.90,$100.90,$100.70,$100.90,$100.40,$101.20,"$268,000.00","$290,000.00","$237,900.00","$315,500.00","$191,200.00","$186,200.00"
4,Ontario,May 2005,$101.30,$101.30,$100.90,$101.30,$100.70,$102.10,"$269,100.00","$291,000.00","$238,300.00","$316,800.00","$191,700.00","$187,800.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5097,Winnipeg,Aug 2023,$285.30,$296.30,$286.10,$313.90,$259.20,$211.00,"$345,200.00","$363,000.00","$335,600.00","$405,500.00","$296,800.00","$223,500.00"
5098,Winnipeg,Sep 2023,$285.70,$296.40,$285.30,$315.20,$261.30,$214.40,"$345,700.00","$363,100.00","$334,600.00","$407,300.00","$299,200.00","$227,000.00"
5099,Winnipeg,Oct 2023,$285.10,$295.00,$285.10,$313.50,$267.70,$216.60,"$345,000.00","$361,400.00","$334,400.00","$405,100.00","$306,500.00","$229,400.00"
5100,Winnipeg,Nov 2023,$282.40,$292.50,$283.10,$308.40,$266.00,$214.10,"$341,700.00","$358,300.00","$332,100.00","$398,400.00","$304,600.00","$226,700.00"
5101,Winnipeg,Dec 2023,$283.40,$292.80,$281.60,$312.00,$273.20,$217.50,"$342,900.00","$358,700.00","$330,300.00","$403,100.00","$312,800.00","$230,300.00"

In [26]:
concat_df.to_csv("Output/real_estate_clean.csv",
                  encoding="utf-8", index=False, header=True)